### ISSUE TITLE
[doc] Update individual marker nodes usage about parameter usage

### ISSUE THREAD

**Issue by 130s** [sniekum/ar_track_alvar#108]
Now that #99 is merged in, [document](http://wiki.ros.org/ar_track_alvar#ar_track_alvar.2BAC8-post-fuerte.Usecase_per_number_of_tags) needs to be updated (otherwise no one uses this nice new feature).

If @achim-k is interested in taking this that'll be great since you're the author of #99 (but no pressure ;) ).

**Comment by achim-k** [comment]
I would be interested :wink: Could we include #100 in the new release? Then I can document that additional parameter directly too.

Edit: Ah Ok I've seen you created a release already, never mind.

**Comment by 130s** [comment]
@achim-k Yes now all PRs are merged in, you should be able to update the doc with the changes you contributed. Thanks!

**Comment by achim-k** [comment]
Will do so, still waiting for being whitelisted for updating the wiki page. Thanks again!

**Comment by achim-k** [comment]
I have troubles finding the right place to edit on the ros wiki. The wiki text editor just shows a few lines like the following
```
{{{#!wiki version groovy_and_newer
<<Include(ar_track_alvar/post-fuerte)>>
}}}
```
and I'm struggling to find the files that are actually included. Could you point me in the right direction? Thanks

**Comment by 130s** [comment]
@achim-k Yeah you hit the tricky part of ROS wiki. It's here: http://wiki.ros.org/ar_track_alvar/post-fuerte

**Comment by 130s** [comment]
This issue was moved to ros-perception/ar_track_alvar#17
