### ISSUE TITLE
Segmentation fault with uncalibrated camera

### ISSUE THREAD

**Issue by liborw** [sniekum/ar_track_alvar#11]
When the camera is not calibrated the node (tested with individualMarkersNoKinect but the rest will be the same) crashes with Segmentation fault.

The problem is in the `Camera::camInfoCallback` the D vector is empty when the camera is not calibrated.

**Comment by sniekum** [comment]
I can't get to this bug fix any time soon, but it would be a simple fix to ignore an empty D vector, as it only appears in one file. If you'd like to fix this, I would happily merge a pull request. 

Scott
