### ISSUE TITLE
Test issues

### ISSUE THREAD

**Issue by achim-k** [sniekum/ar_track_alvar#117]
Here a couple more issues that I noticed concerning the tests:
### Tf lookup issues
When looking at `ar_track_alvar/rosunit-marker_quarternions_WITHARG_CONFIGBASIC.xml`, it is full with 
```
[\\ERROR] [\\/marker_quarternions_WITHARG_CONFIGBASIC]: \\"camera" passed to lookupTransform argument target_frame does not exist.  target_frame=/ar_marker_0
[\\ERROR] [\\/marker_quarternions_WITHARG_CONFIGBASIC]: \\"camera" passed to lookupTransform argument target_frame does not exist.  target_frame=/ar_marker_0
...
```
error messages. The reason for this is probably because of [these](https://github.com/sniekum/ar_track_alvar/blob/a1e635163452700d7af363cc5ad93e2b51e487b2/test/test_ar.py#L87) lines:
```py
while not rospy.is_shutdown():
  try:
    target_frame = '/ar_marker_{}'.format(i)
    (trans, rot) = self.tflistener.lookupTransform('/camera', target_frame, rospy.Time(0))
```
In the rosbag there is no tf information, so the `camera` frame doesn't exist (hence the lookup fails). A possible solution to this would be to add a `tf2_ros/static_transform_publisher` node to [test_markerdetect.launch.xml](https://github.com/sniekum/ar_track_alvar/blob/a1e635163452700d7af363cc5ad93e2b51e487b2/test/test_markerdetect.launch.xml) that makes sure the `camera` frame exists in tf:
```xml
<node pkg="tf2_ros" type="static_transform_publisher" name="camera_tf_pub" args="0 0 0 0 0 0 world camera" />
```
Also, I would maybe add a timeout to the `while`-loop above that makes the test fail if the requested transform couldn't be looked up.

Alternatively we don't look at the tf output but instead at the `/ar_pose_marker` output topic?

### Test_result file content invalid
Another issue I'm having is that the test_result files for the `marker_recog_hz_<TEST>` tests only contain the following line: 
```xml
<?xml version="1.0" encoding="utf-8"?>
```
This causes our jenkins server to spit the following errors:
```
rosunit-marker_recog_hz_WITHARG_CONFIGBASIC.xml.[failed-to-read]
rosunit-marker_recog_hz_WITHARG_CONFIGFULL.xml.[failed-to-read]
rosunit-marker_recog_hz_WITHPARAM_CONFIGBASIC.xml.[failed-to-read]
rosunit-marker_recog_hz_WITHPARAM_CONFIGFULL.xml.[failed-to-read]
```
Not sure though if this is not a `rostest/hztest` issue.

**Comment by 130s** [comment]
This issue was moved to ros-perception/ar_track_alvar#14
