### ISSUE TITLE
ar_marker_x (x name of tag)   passed to lookupTransform argument source_frame does not exist. 

### ISSUE THREAD

**Issue by GPRAMESH** [sniekum/ar_track_alvar#119]
I am using kinectv2 sensor to track ar bundle tags. This is my launch file 
<launch>
  
  <node pkg="tf" type="static_transform_publisher" name="world" args="0 0 0.5 0 0 1.57 /world /kinect2_rgb_optical_frame 100"/>
 
  <arg name="marker_size" default="4.4" />
    <arg name="max_new_marker_error" default="0.08" />
    <arg name="max_track_error" default="0.0" />

	
    
    <arg name="cam_image_topic" default="/kinect2/qhd/points" />
    <arg name="cam_info_topic" default="/kinect2/qhd/camera_info" />

    <arg name="output_frame" default="/world" />
    <arg name="med_filt_size" default="10" />
    <arg name="bundle_files" default="$(find ar_track_alvar)/bundles/truthTableLeg.xml $(find ar_track_alvar)/bundles/table_8_9_10.xml" />

    <node name="ar_track_alvar" pkg="ar_track_alvar" type="findMarkerBundles" respawn="false" output="screen" args="$(arg marker_size) $(arg max_new_marker_error) $(arg max_track_error) $(arg cam_image_topic) $(arg cam_info_topic) $(arg output_frame) $(arg med_filt_size) $(arg bundle_files)" />
</launch>

and output in terminal when i run roslaunch ar_track_alvar pr2_bundle.launch

[ERROR] [1491473505.410939797]: ERROR InferCorners: "ar_marker_9" passed to lookupTransform argument source_frame does not exist. 
[ERROR] [1491473507.343496530]: ERROR InferCorners: "ar_marker_10" passed to lookupTransform argument source_frame does not exist. 
 Can any one help me how to sort out this??

Thank you

**Comment by 130s** [comment]
This issue was moved to ros-perception/ar_track_alvar#13
