### ISSUE TITLE
Move to ros-perception org?

### ISSUE THREAD

**Issue by 130s** [sniekum/ar_track_alvar#122]
- [x] Open a new repo https://github.com/sniekum/ar_track_alvar/issues/122#issuecomment-297643248
- [x] Move issues, PRs --> https://github.com/sniekum/ar_track_alvar/issues/122#issuecomment-297686288
- [x] Update dev repo in rosdistro --> https://github.com/ros/rosdistro/pull/14698
- [x] Deprecation notice https://github.com/sniekum/ar_track_alvar/issues/122#issuecomment-297686743

----

@sniekum Occasionally I have had to ask you for admin tasks, and there will still be some cases I/someone have to.
- Do you mind giving me an admin access to this repo?
- Alternatively, even better is to fork this to somewhere OSRF manages, e.g. [ros-perception](https://github.com/ros-perception/) org unit. 
  - Benefit is, you'll be freed from any admin chores, and the package will probably get even more visibility (despite the popular this package has already got). You'll remain the author of course.
  - Drawback is people who downloaded the source will have to adjust their `git remote` to the new repo's location.

**Comment by sniekum** [comment]
This is just a normal user repo, so I can’t give you admin access without actually transferring ownership of the repo to you (which is an option we can consider).  I’m also fine with moving this to ros-perception.  What do you think is best?

—Scott

**Comment by 130s** [comment]
Thanks, I didn't know the limitation of a normal user repo.
Then, I prefer to "fork"ing the repo to `ros-perception` or somewhere under `ros-*` and make that as an official, so that we'll be free from the number of admins limit.

@wjwwood could you fork this repo to a GitHub org unit somewhere appropriate that OSRF maintains, and add @sniekum and @130s as admin?

**Comment by wjwwood** [comment]
Yes sir: https://github.com/ros-perception/ar_track_alvar

**Comment by 130s** [comment]
Thanks @ wjwwood.

> - [ ] Move issues, PRs

Using [github-issues-import](https://github.com/IQAndreas/github-issues-import), after successfully imported 12 issues/PRs only, the import stopped (I might have hit https://github.com/IQAndreas/github-issues-import/issues/41) So I manually imported ONLY open issues 1by1 using https://github-issue-mover.appspot.com/ As a result, only 12 closed issues/merged PRs, all 25 open issues are moved, have been moved to the new repo.

> - [ ] Update dev repo in rosdistro

Done https://github.com/ros/rosdistro/pull/14698

**Comment by 130s** [comment]
@sniekum hopefully one last thing; could you update at the top page of this repo the summary as something like "MOVED TO https://github.com/ros-perception/ar_track_alvar"?

**Comment by carlosjoserg** [comment]
Hi guys, apologies to jump in, it might save you time.

Adding contributors with write access is feasible even for normal users.

Though I believe the best option would be to transfer ownership of the repo, which ill copy issues and PRs plus avoid confusion and it's cleaner. 

Although changing the remotes is recommended, github handles all traffic forwarding very well, I have used it before. Check the last item here: https://help.github.com/articles/about-repository-transfers/

But of course all up to you!

**Comment by 130s** [comment]
> @sniekum hopefully one last thing; could you update at the top page of this repo the summary as something like "MOVED TO https://github.com/ros-perception/ar_track_alvar"?

@sniekum friendly ping :)
Recently there was still a pull request against this repo.

**Comment by sniekum** [comment]
Done.

**Comment by 130s** [comment]
Thank you @sniekum!
