### ISSUE TITLE
7-bit marker detection

### ISSUE THREAD

**Issue by swarmlab** [sniekum/ar_track_alvar#13]
All current nodes don't accept arguments for x-bit markers and x-bit borders. So Marker detection is currently only enabled for 5-bit markers.
To fix this, marker_detector.SetMarkerSize(marker_size); has to be adjusted to   marker_detector.SetMarkerSize(marker_size, bitsize, bordersize);

**Comment by sniekum** [comment]
Thanks for the heads up.  Things are very busy now on my end -- would you
mind submitting a pull request?  Thanks.

--Scott
