### ISSUE TITLE
Symbol look up error

### ISSUE THREAD

**Issue by brawner** [sniekum/ar_track_alvar#18]
It doesn't appear that the apt package is properly built for Hydro. I get the following error when trying to run individualMarkers.

```
/opt/ros/hydro/lib/ar_track_alvar/individualMarkers: symbol lookup error: /opt/ros/hydro/lib/libar_track_alvar.so: undefined symbol: _ZN3ros7console5printEPNS0_10FilterBaseEPvNS0_6levels5LevelEPKciS7_S7_z
```

**Comment by brawner** [comment]
Building from source seems to get past this error

**Comment by sniekum** [comment]
There were some funny errors that got emailed to me from the build farm
last week, so I think there's something funny going on with the Hydro
build. Glad it works from source.

**Comment by brawner** [comment]
So, it looks like this package requires rosbag_storage, but that doesn't get installed with apt. Or at least, when I installed rosbag_storage from apt, the apt version of ar_track_alvar started working fine.

**Comment by sniekum** [comment]
Hm, I can't think of any reason ar_track_alvar would have any dependencies
on rosbag.  Maybe just a coincidence?

**Comment by brawner** [comment]
Quite possibly it was a dependency thing on my end. I'll let you know if I can reproduce
