### ISSUE TITLE
medianFilter lib not installed

### ISSUE THREAD

**Issue by mateiciocarlie** [sniekum/ar_track_alvar#19]
Looks like medianFilter is missing from the install targets in CMakeLists - as such, the debian package does not have it, and findMarkerBundles balks...

**Comment by krisdestruction** [comment]
Even when I run "cmake ." in the directory, there are cmake errors:

CMake Error at CMakeLists.txt:10 (find_package):
  Could not find module Findcatkin.cmake or a configuration file for package
  catkin.

  Adjust CMAKE_MODULE_PATH to find Findcatkin.cmake or set catkin_DIR to the
  directory containing a CMake configuration file for catkin.  The file will
  have one of the following names:

```
catkinConfig.cmake
catkin-config.cmake
```

CMake Error at CMakeLists.txt:22 (find_package):
  Could not find module FindEigen.cmake or a configuration file for package
  Eigen.

  Adjust CMAKE_MODULE_PATH to find FindEigen.cmake or set Eigen_DIR to the
  directory containing a CMake configuration file for Eigen.  The file will
  have one of the following names:

```
EigenConfig.cmake
eigen-config.cmake
```

CMake Error at CMakeLists.txt:23 (find_package):
  Could not find module FindOpenCV.cmake or a configuration file for package
  OpenCV.

  Adjust CMAKE_MODULE_PATH to find FindOpenCV.cmake or set OpenCV_DIR to the
  directory containing a CMake configuration file for OpenCV.  The file will
  have one of the following names:

```
OpenCVConfig.cmake
opencv-config.cmake
```

CMake Error at CMakeLists.txt:30 (add_message_files):
  Unknown CMake command "add_message_files".

-- Configuring incomplete, errors occurred!
