### ISSUE TITLE
"Master" tag in bundle jumping around

### ISSUE THREAD

**Issue by mateiciocarlie** [sniekum/ar_track_alvar#20]
Trying to detect a bundle; what I am getting is the following: all tags are nice and stable, except for the "master" tag (which I guess is considered to be the first one in the xml file?) which is in the wrong spot and jumps around. Attaching screenshots with markers; xml file is below.

Any thoughts much appreciated!

```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<multimarker markers="5">
    <marker index="0" status="2">
        <corner x="-2.25" y="-2.25" z="0.0" />
        <corner  x="2.25" y="-2.25" z="0.0" />
        <corner  x="2.25"  y="2.25" z="0.0" />
        <corner x="-2.25"  y="2.25" z="0.0" />
    </marker>
    <marker index="1" status="2">
        <corner x="71.25" y="-2.25" z="0.0" />
        <corner x="75.75" y="-2.25" z="0.0" />
        <corner x="75.75"  y="2.25" z="0.0" />
        <corner x="71.25"  y="2.25" z="0.0" />
    </marker>
    <marker index="2" status="2">
        <corner x="144.75" y="-2.25" z="0.0" />
        <corner x="149.25" y="-2.25" z="0.0" />
        <corner x="149.25"  y="2.25" z="0.0" />
        <corner x="144.75"  y="2.25" z="0.0" />
    </marker>
    <marker index="3" status="2">
        <corner x="-2.25" y="-76.25" z="0.0" />
        <corner  x="2.25" y="-76.25" z="0.0" />
        <corner  x="2.25" y="-71.75" z="0.0" />
        <corner x="-2.25" y="-71.75" z="0.0" />
    </marker>
    <marker index="6" status="2">
        <corner x="-2.25" y="-150.25" z="0.0" />
        <corner  x="2.25" y="-150.25" z="0.0" />
        <corner  x="2.25" y="-145.75" z="0.0" />
        <corner x="-2.25" y="-145.75" z="0.0" />
    </marker>
</multimarker>
```

![ar1](https://f.cloud.github.com/assets/2230382/2115345/39d99fe8-904e-11e3-8535-77f22d425d51.png)

![ar2](https://f.cloud.github.com/assets/2230382/2115346/3d58bd48-904e-11e3-90d2-0160981fbbca.png)

**Comment by sniekum** [comment]
Matei,

It looks like you might be an order of magnitude off on your measurements.
The xml file should contain measurements of the corners of the tags, in
centimeters, from the center of the master tag.  It looks like you are
probably using millimeters for some of the measurements (like 144.75 seems
way too large.  Actually 14.475 cm even seems pretty big based on what I
can tell from the picture...)  Let me know if that fixes things.

--Scott

**Comment by sniekum** [comment]
Only some of the measurements seem wrong though.  The 2.25 ones seem about
right.  Just try changing the other ones.

**Comment by mateiciocarlie** [comment]
Yes! That was the problem. I am used to mm being the length unit throughout ROS, so I introduced the error in the other entries in the XML file. Thanks!

As a side note, are there a few words somewhere about _how_ the bundle detector operates? I suppose one can always try to figure it out from code, but was just wondering if it's spelled out somewhere.

**Comment by sniekum** [comment]
The only official documentation is the ar track alvar entry on the ROS wiki. If you have other questions about the inner workings of things though, feel free to mail me.
