### ISSUE TITLE
roslaunch error

### ISSUE THREAD

**Issue by krisdestruction** [sniekum/ar_track_alvar#21]
Under the /opt/ros/hydro/share directory, I ran: 
sudo git clone https://github.com/sniekum/ar_track_alvar.git

Then I changed directory to the package:
cd ar_track_alvar/

I ran rosmake:
rosmake

Then I roslaunched the individual no kinect launch file:
roslaunch ar_track_alvar pr2_indiv_no_kinect.launch

It returns the error:
ERROR: cannot launch node of type [ar_track_alvar/individualMarkersNoKinect]: can't locate node [individualMarkersNoKinect] in package [ar_track_alvar]

**Comment by jihoonl** [comment]
/opt/ros/hydro is designated place to install deb packages. You may not want to install source version in there.
do the following command instead.

```
> sudo apt-get install ros-hydro-ar-track-alvar
```

If you want to get a source version, install them in your catkin workspace.

**Comment by ajayjain** [comment]
I ran `sudo apt-get install ros-hydro-ar-track-alvar`, but when trying to run ar_track_alvar/individualMarkersNoKinect from a launch file, I get the error: `ERROR: cannot launch node of type [ar_track_alvar/individualMarkersNoKinect]: can't locate node [individualMarkersNoKinect] in package [ar_track_alvar]`. The executable is located in `/opt/ros/hydro/lib/ar_track_alvar/individualMarkersNoKinect`, and I can run that directly.

Doesn't work:
    rosrun ar_track_alvar individualMarkersNoKinect 1.2 0.08 0.2 /camera/image_raw /camera/camera_info /camera
Doesn't work:

```
    <launch>
        <node name="ar_track_alvar" pkg="ar_track_alvar" type="individualMarkersNoKinect" respawn="false" output="screen" args="$(arg marker_size) $(arg max_new_marker_error) $(arg max_track_error) $(arg cam_image_topic) $(arg cam_info_topic) $(arg output_frame)" />
    </launch>
```

My ROS_PACKAGE_PATH is /opt/ros/hydro/share:/opt/ros/hydro/stacks:/home/ajay/catkin_ws:/home/ajay/catkin_ws/src:/home/ajay/catkin_ws/src/phidgets.
