### ISSUE TITLE
Building on ARM

### ISSUE THREAD

**Issue by ggregory8** [sniekum/ar_track_alvar#23]
Hi guys,

Is ar_track_alvar debian install available for ARM architecture? More specifically I am trying to build on a Odroid-U3. Or must I try to build from source? If so has anyone had any success with this?

Linaro 12.11
armv7l 
GNU/Linux

Thanks.

**Comment by sniekum** [comment]
You'll need to build from source, but I have never attempted that for ARM.

**Comment by ggregory8** [comment]
For anyone else wanting to know. Once I installed all the dependencies I was successfully able to build from source on a armv7 system (Odroid-U3) running Ubuntu 12.04.
