### ISSUE TITLE
How to install into Hydro 32bit PC

### ISSUE THREAD

**Issue by wyasuda** [sniekum/ar_track_alvar#26]
Dear all:

I would like to install this attractive ar_track_alvar package into my PC.
Unfortunately, it is still 32 bit.
Would you please tell me how to install?
I use ROS Hydro.

Thank you in advance.

**Comment by rethink-rlinsalata** [comment]
@wyasuda - You can check out the changes in the groovy branch to support 32-bit -- see PR #25 (just the 4 commits there or the merge commit 0efad060a3920d9e422a0d64f0470ad68a7c1f7d).

I don't think there was anything groovy-specific, so you can probably try just grabbing the diff of those 4 commits and patching it on to the hydro-devel branch to test locally first.

**Comment by wyasuda** [comment]
Thank you for your advice.
Before I edit them manually in accordance with 0efad06,  I checked out hydro-devel branch at my local PC and run catkin_make.
I got following error messages.
Would you tell me how to deal with them?

-- +++ processing catkin package: 'ar_track_alvar'
-- ==> add_subdirectory(ar_track_alvar)
-- Using these message generators: gencpp;genlisp;genpy
CMake Error at /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:72 (find_package):
  Could not find a configuration file for package cmake_modules.

  Set cmake_modules_DIR to the directory containing a CMake configuration
  file for cmake_modules.  The file will have one of the following names:

  cmake_modulesConfig.cmake
  cmake_modules-config.cmake

Call Stack (most recent call first):
  ar_track_alvar/CMakeLists.txt:10 (find_package)

-- Eigen found (include: /usr/include/eigen3)
CMake Error at ar_track_alvar/CMakeLists.txt:28 (find_package):
  Could not find module FindTinyXML.cmake or a configuration file for package
  TinyXML.

  Adjust CMAKE_MODULE_PATH to find FindTinyXML.cmake or set TinyXML_DIR to
  the directory containing a CMake configuration file for TinyXML.  The file
  will have one of the following names:

  TinyXMLConfig.cmake
  tinyxml-config.cmake

-- ar_track_alvar: 2 messages, 0 services

**Comment by wyasuda** [comment]
Now I understand I do not need to edit files manually.
I could use 'cherry-pick'.
Still I have to deal with the error above.

**Comment by rethink-rlinsalata** [comment]
The tiny xml sounds like it could be related to that other pull request, #24 I believe. Maybe a rosdep you need to install. In fact, the cmake modules is mentioned in that commit too, you might want to check with @bulwahn about it.

**Comment by wyasuda** [comment]
Thank you for your advice.

I tried the commands below.

```
roscd ar_track_alvar
rosdep install ar_track_alvar
cd ../..
catkin_make
```

And saw compile succeeded!
Thank you so much!

Now I tried the following commands.

```
roscd ar_track_alvar
git cherry-pick 0efad06
```

Then I got following message.
error: Commit 0efad060a3920d9e422a0d64f0470ad68a7c1f7d is a merge but no -m option was given.
fatal: cherry-pick failed

Does it mean I could not use cherry-pick?
Would you tell me if I have to edit these files manually?

**Comment by wyasuda** [comment]
Now I understand that 0efad06 is a merge with two parents so I have to tell the cherry-pick command which one against which the diff should be calculated, by using the -m option.
Or I have to do cherry-pick 4 times for each of your 4 commits.
Would you tell me which one is better?

**Comment by wyasuda** [comment]
Finally, I have succeeded to compile them.
I did cherry-pick 4 times.
I could see the markers on Rviz.
Thank you!

[100%] Built target findMarkerBundles
[100%] Built target individualMarkers
Linking CXX executable /home/wataru/catkin_ws_hydro/devel/lib/ar_track_alvar/trainMarkerBundle
Linking CXX executable /home/wataru/catkin_ws_hydro/devel/lib/ar_track_alvar/individualMarkersNoKinect
[100%] Built target trainMarkerBundle
[100%] Built target individualMarkersNoKinect
