### ISSUE TITLE
indigo release?

### ISSUE THREAD

**Issue by jihoonl** [sniekum/ar_track_alvar#27]
Will anybody do this? :smile:

**Comment by jihoonl** [comment]
@sniekum  I would like to release the deb in indigo. Is there anything I can help you with?

**Comment by sniekum** [comment]
I'm on vacation with just my phone so there's not much I can do. I've made you a collaborator on the repo if you'd like to do the release yourself.

**Comment by jihoonl** [comment]
Ok. Thanks. I will create `indigo-devel` branch and work on the release.

**Comment by jihoonl** [comment]
I would like to separate msg and source package before release. It should be middle step for discussion in #28.

How should I name the packages? These are my initial thought.

Meta : `ar_track_alvar_meta`
msg : `ar_track_alvar_msgs`
source : `ar_track_alvar`

**Comment by jihoonl** [comment]
ar_track_alvar is now available in indigo shadow-fixed.
