### ISSUE TITLE
Split msgs into a separate repo

### ISSUE THREAD

**Issue by stonier** [sniekum/ar_track_alvar#28]
This is just a request to split the messages into a separate repo. Currently it is difficult to get the messages for platforms that can't easily compile ar_track_alvar and its dependencies since the library too has to be compiled at the same time (e.g. android, cross compiling) but they will often want to communicate with an ar_track_alvar node.

**Comment by stonier** [comment]
If it's easier, we can create and test with a msg repo and request to move it alongside a modified (pull request) version of this one.

**Comment by rethink-rlinsalata** [comment]
Both the main ROS Package and a split out msgs ROS Package could both reside in this same repo and make this a meta-package repo -- that way you'd be able to keep the messages together with the rest of the code, but access them separately.

**Comment by sniekum** [comment]
I agree with Rob -- meta-package is the way to go.  Separation is good, but
I want to keep it all together in the same repo.

**Comment by stonier** [comment]
Splitting into a package in the same repo doesn't actually help. Whether the messages are in the same package, or in a package to the side but in the same repo the same difficulty is still there.

Source installing the repo to build messages when cross/windows/android-compiling will still require compilation of the source package regardless. The only workaround is to manually CATKIN_IGNORE packages which breaks automation and quickly becomes impractical.

This is why most ros msg packages have migrated from being included in the source packages (pre boxturtle) to independent msg stacks like common_msgs. Its a very practical way of giving out your ros api to people who need only communicate with your nodes.

Is there a strong reason for wanting to keep it together?

**Comment by sniekum** [comment]
There are a large number of people that already use this package, and the
separation would break things for a lot of people in an easy-to-fix, but
annoying way.   I'd rather not do that.

Maybe there can be a parallel repo with just the messages (and since the
messages will likely never change, it shouldnt require upkeep) for people
who want it?

**Comment by stonier** [comment]
> There are a large number of people that already use this package, and the
> separation would break things for a lot of people in an easy-to-fix, but
> annoying way.   I'd rather not do that.

If you do this in a rosdistro upgrade (it would be an api breaking change inside a rosdistro version), is it actually an imagined issue? The community coped with the common_msgs migration and I can't remember seeing any complaints at all - I think for most, like me, it was a clear separation of code from api with practical benefits that was worth the minor effort in patching my own code when upgrading to the next ros distro.

> Maybe there can be a parallel repo with just the messages (and since the
> messages will likely never change, it shouldnt require upkeep) for people
> who want it?

Aye, that should work, but really seems hackish and unintuitive. It also increases maintenance for you (always an undesirable effect!). If you were looking at supporting legacy users, perhaps having c++ headers and python modules that redirect (via includes and imports) with deprecation warnings would do the job more constructively. 

If this is all uncomfortably pushing you in a direction you don't want to go though, that's ok (just let me know). We can always fork, but I thought I'd try and find a way to work with upstream before taking that step.

**Comment by sniekum** [comment]
For now I'd prefer if you just forked it.  I'm leaving for travel tomorrow
for two weeks, and don't have time to do anything right now.  I'll think
about other possible solutions in the future, but honestly, this is the
first request I've ever gotten about this.  I usually get 5-10 other
questions/requests/comments/complaints to my personal email a week about
this package, and I have a feeling a lot of other people would be annoyed
(and let it be known in my inbox).

**Comment by stonier** [comment]
I suspect most ros groups are still in research labs where they don't have to leave the conveniences of ros-intel-ubuntu. Even if they want to, there are often many awkward blocks (like this) that make it not worth the effort for research.

**Comment by sniekum** [comment]
@stonier Does this newest indigo update help you?  Or do you definitely need it split into a separate package?  I'm starting to think that even though I don't want to mess with the hydro and earlier versions, it is a good idea to separate the msgs starting in indigo.  Maybe coordinate with Jihoon and let him know what works best for your type of use case, since he is handling this issue.

**Comment by jihoonl** [comment]
Considering his usecase, he would be happy if msg is independent repository. He has been contributing on uncommon ROS development infrastructures like rosjava and win-ros. So I think his use cases are coming from difficulty of porting on different platforms.

There are two use cases that msg repo separation may help.

**Windows ROS**

Some people use ubuntu for robot(like turtlebot) and use Windows machine for introspection and computing purpose. In this case, window’s machine does not need ar_track_alvar package but its message to process.

To use ar_track_alvar package message at the moment, user need to do three steps. 1) git clone or wstool the package, 2) restructure it to compile msg only, 3) and compile.

If the msg is separated, user can use wstool to clone all necessary repos and compile easily without manual changes.

win-ros : http://wiki.ros.org/hydro/Installation/Windows#win_ros.2BAC8-hydro.Information

**ROSJava**

rosjava also uses different approach to generate msgs as Java class. I am not an expert on this to explain in detail but I remember I had enough headache to get all the messages working in Android last time.

rosjava : http://wiki.ros.org/rosjava?distro=hydro

**Conclusion**

Thus, I would also suggest to have msg as separate repo and provide rosinstall file for source installation users. If you can create ar_track_alvar_msgs, I will proceed the necessary changes

**Comment by sniekum** [comment]
Thanks for the in-depth info Jihoon.  I've created an ar_track_alvar_msgs repo and added you as a collaborator.

**Comment by stonier** [comment]
@jihoonl :+1: 

Thanks for the elaborate response, it explains everything well.

**Comment by jihoonl** [comment]
This issue is also resolved in indigo release https://github.com/sniekum/ar_track_alvar/issues/27
