### ISSUE TITLE
Use without a PR2

### ISSUE THREAD

**Issue by BenBlumer** [sniekum/ar_track_alvar#30]
Hi all,

I'm trying to get this to work using just a webcam. For now, I want to get the coordinates of the tag relative to the webcam.  So I've written a launch file to establish a transformation (an identity transform) and to launch the individualMarkersNoKinect node. Separately, I'm launching a usb_cam usb_cam_node from the usb_cam package. The usb_cam_node seems to work -- as I can get a bunch of data from it using `rostopic echo /usb_cam/image_raw`.

The launch file I'm using is this:

```
   <launch>
   <node pkg="tf" type="static_transform_publisher" name="id_trans_bm" args="0 0 0 0 0 0 world idtrans 100" />

    <arg name="marker_size" default="5.5" />
    <arg name="max_new_marker_error" default="0.08" />
    <arg name="max_track_error" default="0.2" />
    <arg name="cam_image_topic" default="/usb_cam/image_raw" />
    <arg name="cam_info_topic" default="/usb_cam/camera_info" />    
  <arg name="output_frame" default="/idtrans" /> 

    <node name="ar_track_alvar" pkg="ar_track_alvar" type="individualMarkersNoKinect" respawn="false" output="screen" args="$(arg marker_size) $(arg max_new_marker_error) $(arg max_track_error) $(arg cam_image_topic) $(arg cam_info_topic) $(arg output_frame)" />
</launch>
```

When I run this, I get:

```
...
[ INFO] [1402705988.330448089]: Subscribing to image topic
[ERROR] [1402705989.598987066]: "head_camera" passed to lookupTransform argument source_frame does not exist. 
```

Can this be made to work?

**Comment by BenBlumer** [comment]
head_camera is the frame_id being published by the camera_info topic of usb_cam by default.  Even though the name is specified, it doesn't exist until you define it.  I'll close the issue for now, but I'll update it with a minimum working example soon.  

I'll also send a pull request when I have an example launch file for use with a webcam and usb_cam package.

**Comment by simonbogh** [comment]
Hi Ben,

Did you ever get this to work, and perhaps make a minimum working example for a webcam?

I seem to be able to track the markers, but their pose is just put directly on top of the camera frame.

**Comment by BenBlumer** [comment]
Hey:

I actually ended up not using ar_track_alvar for my thesis, but I did get it working and I have some notes from that. 

Try this launch file and let me know if it works for you. 

```
<launch>
  <arg name="camera" default="camera" />

  <arg name="pi/2" value="1.5707963267948966" />
  <arg name="camera_transformation" value="0 0 0 0 0 0" />
    <node pkg="tf" type="static_transform_publisher" name="$(arg camera)_base_link3"
        args="$(arg camera_transformation) /world /head_camera 100" />  
    <arg name="marker_size" default="6" />
    <arg name="max_new_marker_error" default="0.08" />
    <arg name="max_track_error" default="0.2" />
    <arg name="cam_image_topic" default="/usb_cam/image_raw" />
    <arg name="cam_info_topic" default="/usb_cam/camera_info" />    
    <arg name="output_frame" default="/head_camera" />

    <node name="ar_track_alvar" pkg="ar_track_alvar" type="individualMarkersNoKinect" respawn="false" output="screen" args="$(arg marker_size) $(arg max_new_marker_error) $(arg max_track_error) $(arg cam_image_topic) $(arg cam_info_topic) $(arg output_frame)" />
</launch>
```

**Comment by hemangchawla** [comment]
Hi Ben,

Could you please share which package did you eventually used?

**Comment by BenBlumer** [comment]
Hey there,

Did you try the launch file I posted above? I got that to work fine. Though, ultimately for my project, I decided to use a stereovision solution.

**Comment by hemangchawla** [comment]
yes, thanks Ben.

I changed that and also made some changes in the cpp source files of the package to make the tracking work with an ir camera. I as just curious what you eventually used, hence asked.
