### ISSUE TITLE
Integrate kinect data

### ISSUE THREAD

**Issue by Raffa87** [sniekum/ar_track_alvar#34]
On the description of package at http://wiki.ros.org/ar_track_alvar it is declared: 

> "Identifying and tracking the pose of individual AR tags, optionally integrating kinect depth data (when a kinect is available) for better pose estimates."

How can I integrate my kinect data in the process?
Thank you

**Comment by rethink-rlinsalata** [comment]
The default launch files and executables integrate the Kinect data automatically.  If you use the "\* NoKinect" variants, then it will not use the kinect.

There are four executables/launch files: one for Individual Markers, one for Bundles of Markers, and a "No Kinect" version for each of the first two.

**Comment by Raffa87** [comment]
I'm working on fuerte on a 32bit machine so I followed the instructions explained in: http://wiki.ros.org/ar_track_alvar:

git clone https://github.com/sniekum/ar_track_alvar.git
git checkout f093668

and the launch file that I got, the node subscribe to Image topic rather than PointCloud. Is there the chance to integrate PointCloud data also in fuerte on a 32 bit?
Thanks!

**Comment by 130s** [comment]
This issue was moved to ros-perception/ar_track_alvar#36
