### ISSUE TITLE
Not enough inliers found to support a model - Ignoring transform for child_frame_id

### ISSUE THREAD

**Issue by TSC21** [sniekum/ar_track_alvar#35]
Hi,

I'm using an Asus Xtion Pro Live to identify and track the pose of numb 8 AR tag, integrating the driver depth data. I'm using Openni2 with ROS Hydro in Ubuntu 12.11 Linaro, on a ARM architecture (a Odroid to be more specific). I have PCL-1.7 installed by deb packages (which was required by pcl-ros). My launch file has the following config:

```
<arg name="cam_image_topic" default="/camera/depth_registered/points" />
<arg name="cam_info_topic" default="/camera/rgb/camera_info" />     
<arg name="output_frame" default="/camera_link" />

<node name="ar_track_alvar" pkg="ar_track_alvar" type="individualMarkers" respawn="false" output="screen" args="$(arg marker_size) $(arg max_new_marker_error) $(arg max_track_error) $(arg cam_image_topic) $(arg cam_info_topic) $(arg output_frame)" />
```

</launch>

I get the following log in command line:

******\* ID: 8
[pcl::SampleConsensusModelPlane::optimizeModelCoefficients] Not enough inliers found to support a model (0)! Returning the same coefficients.

Error:   TF_NAN_INPUT: Ignoring transform for child_frame_id "ar_marker_8" from authority "/ar_track_alvar" because of a nan value in the transform (nan nan nan) (nan nan nan nan)
         at line 240 in /tmp/buildd/ros-hydro-tf2-0.4.10-0precise-20140219-1739/src/buffer_core.cpp

Also in the command line window where I launched openni2_launch openni2.launch I'm getting at the same time:

Error:   TF_NAN_INPUT: Ignoring transform for child_frame_id "ar_marker_8" from authority "/ar_track_alvar" because of a nan value in the transform (nan nan nan) (nan nan nan nan)
         at line 240 in /tmp/buildd/ros-hydro-tf2-0.4.10-0precise-20140219-1739/src/buffer_core.cpp

Any way of solving this? Since I have a RGBD camera I would like to use it's depth for better pose estimation. The simpler node without depth data works though.
Thanks in advance!

**Comment by LoyVanBeek** [comment]
I'm having similar problem, using a Kinect:

```
[pcl::RandomSampleConsensus::computeModel] No samples could be selected!
[pcl::SACSegmentation::segment] Error segmenting the model! No solution found.
```

As there errors clutter more important output, I suppress them by forwarding stderr to /dev/null with `roslaunch ... 2> /dev/null`. But thats not a real solution of course.

**Comment by 130s** [comment]
This issue was moved to ros-perception/ar_track_alvar#35
