### ISSUE TITLE
Median Filter Library missing

### ISSUE THREAD

**Issue by rabenimmermehr** [sniekum/ar_track_alvar#38]
Hey guys,

I installed this package via `sudo apt-get install ros-hydro-ar-track-alvar`. When I track isolated markers, everything is fine, but when I want to track a bundle I get an error launching the node:

```
/opt/ros/hydro/lib/ar_track_alvar/findMarkerBundles: error while loading shared libraries: libmedianFilter.so: cannot open shared object file: No such file or directory
```

Did I miss a step or is there something wrong with the code?

Thanks in advance,
Rabe

System Information:
Ubuntu 12.04 64bit
ROS Hydro

**Comment by MZofka** [comment]
I'm not sure, but try pulling it from the github repository and building it in your own catkin ws. That should work.

**Comment by Uliv** [comment]
Hi Rabe,

I have the same issue and have the same system information as you have. How were you able to resolve it?

Thanks,
Uli

Edit: I was able to resolve the issue by building it in my own catkin ws.

**Comment by 130s** [comment]
This issue was moved to ros-perception/ar_track_alvar#34
