### ISSUE TITLE
Release 0.5.1 (or newer)?

### ISSUE THREAD

**Issue by 130s** [sniekum/ar_track_alvar#41]
Sufficient amount of commits have been merged since 0.5.0 particularly in hydro and indigo. Thanks!

**Comment by sniekum** [comment]
Hi Isaac,

I just updated the package.xml files.  I don't have access to the Bloom
release tools installed at the moment.  Would you mind triggering the
release?

--Scott

**Comment by 130s** [comment]
Ok, thanks. Once #42 is cleared I'll move on.

**Comment by 130s** [comment]
Closed via https://github.com/ros/rosdistro/issues/7930
