### ISSUE TITLE
Mirrored marker false detection

### ISSUE THREAD

**Issue by mehditlili** [sniekum/ar_track_alvar#45]
While doing some tests with the ar markers, I realized that sometimes marker 5 is also detected as being marker 14 where the Z axis goes in the opposite direction. Markers 5 and 14 are mirrored versions of each other. I fixed this by eliminating all markers detected with a z axis in a negative direction but it would be nice to eliminate this problem once for all.

**Comment by 130s** [comment]
This issue was moved to ros-perception/ar_track_alvar#32
