### ISSUE TITLE
update ROS wiki documentation

### ISSUE THREAD

**Issue by bit-pirate** [sniekum/ar_track_alvar#47]
I noticed that the package documentation on the ROS wiki seems heavily out of date, e.g. Fuerte is mentioned in the text.

http://wiki.ros.org/ar_track_alvar

I already create the missing pages for the new meta and message packages and also split the main package doc in a fuerte page for the fuerte version and a post-fuerte page for all following versions.

If you have time please take a look at the wiki page and update where necessary.

**Comment by 130s** [comment]
This issue was moved to ros-perception/ar_track_alvar#31
