### ISSUE TITLE
Release repository distributed

### ISSUE THREAD

**Issue by 130s** [sniekum/ar_track_alvar#48]
@jihoonl I'm making the initial release into Jade (related to #46) and I found [the Indigo release repository of this package is under your organization](https://github.com/ros/rosdistro/blob/d8c840ebfdab635940477448aa0ed20af4f8dc83/indigo/distribution.yaml#L194), instead of [ros-gbp repo used in hydro](https://github.com/ros/rosdistro/blob/6f440516da536f0c69dfca656f4ead19722efa1f/hydro/distribution.yaml#L231) (looks like [this is related](https://github.com/sniekum/ar_track_alvar/issues/27)). If there is no specific reason to separate the release repo, does merging those into ros-gbp one make sense (if so I'll take care of it)?

**Comment by jihoonl** [comment]
Yeah. I couldn't use ros-gbp because of authorization issue. I couldn't push into https://github.com/ros-gbp/ar_track_alvar-release.  Please do it in ros-gbp if you can.

**Comment by 130s** [comment]
Closed via https://github.com/ros/rosdistro/issues/7930
