### ISSUE TITLE
Keyboard Input Broken on Training Node

### ISSUE THREAD

**Issue by knoffelcut** [sniekum/ar_track_alvar#53]
On some systems I experience problems with the keyboard input when using the TrainMarkerBundle node. In particular, the system does not accept any keyboard input. In all tests I have ensured that the OpenCV input window is active.

This bug has been tested on three systems, all running Linux Mint 17.1, using the code compiled from source and from the ROS repositories. On two of these systems no input is accepted, not even the 'q' command to exit the program. For some reason it does work correctly on one of these systems.
### Proposed Solution

I have corrected the code at my end and the node works as intended. The wrong data type is used when reading the keyboard input from OpenCV. The input is read as _int_, while it later parsed by comparing it to _chars_. The following changes has been made in [nodes/TrainMarkerBundle.cpp](https://github.com/sniekum/ar_track_alvar/blob/indigo-devel/nodes/TrainMarkerBundle.cpp) to correct the code:

```
int keyCallback(int key); -> int keyCallback(char key); // Around line 86
int keyProcess(int key) -> int keyProcess(char key) // Around line 318
int key = cvWaitKey(20); -> char key = cvWaitKey(20); // Around line 427
```
### Concerns

I do not wish to commit these changes myself since the reason why they work is unclear to me. The _cvWaitKey(20)_ method returns an _int_. It does not make sense that an earlier conversion to _char_ solved the problem.

**Comment by RonaldEnsing** [comment]
I had the same problem, and this solution worked for me. Thanks!

**Comment by 130s** [comment]
This issue was moved to ros-perception/ar_track_alvar#30
