### ISSUE TITLE
Simpler way to pause detection

### ISSUE THREAD

**Issue by NikolasE** [sniekum/ar_track_alvar#61]
If I run the detector, at least one full core is dedicated to this task. I however don't need the detections always so I'd like to have a way to pause the detection for a while. I saw e.g. in the IndividualMarkersNoKinect.cpp that this could be done with the parameterUpdate, but there is no way to just set the enabled-flag (line 215) without setting all other parameters also. 

I'd propose a simple std_msgs/Bool-Subscriber that would look like

void run_detection_cb(const std_msgs::Bool::ConstPtr& msg)
{
    enableSwitched = enabled != msg->data;
    enabled = msg->data;
}

ros::Subscriber sub_sleep = n.subscribe("run_detection", 1, run_detection_cb);

What do you think? Is that a good addition to the node? It is fully backwards-compatible so it should make any problems. 

I'd create a pull request if you'd later merge it.

**Comment by sniekum** [comment]
Sure, submit a pull request.
