### ISSUE TITLE
Camera position x y z

### ISSUE THREAD

**Issue by fickrie67** [sniekum/ar_track_alvar#68]
Hallo,

thank you very much for the amazing software, i have one question here:
-how do i get the camera position coordinate x y z ? to use it later on as camera tracking

thank you very much

**Comment by achim-k** [comment]
You can use tf for that. See also <http://wiki.ros.org/tf>.

**Comment by 130s** [comment]
This issue was moved to ros-perception/ar_track_alvar#25
