### ISSUE TITLE
Axis orientation difference between individualMarkers and individualMarkersNoKinect

### ISSUE THREAD

**Issue by longjie** [sniekum/ar_track_alvar#69]
Hi,
I'm using Xtion pro live and the individualMarkers node to detect AR marker's position and orientation.
I have noticed the marker's orientation, the direction of x and y axis, is differ from the one from the individualMarkersNokinect. The direction is rotated 90 degrees from the correct direction. The individualMarkersNoKinect node produces correct orientation with the same sensor and image topic.

I don't know this issue is special for my environment. If someone have any advices, please help me.

Environment: Ubuntu 12.04LTS, ROS hydro, ar_track_alvar/hydro-devel branch

**Comment by 130s** [comment]
This issue was moved to ros-perception/ar_track_alvar#24
