### ISSUE TITLE
Marker detection with changed margin size is impossible

### ISSUE THREAD

**Issue by StephanOpfer** [sniekum/ar_track_alvar#72]
Hi all,

we created marker, which have a margin of size 1. How do we change the margin size for the detection? We were only able to checkout the repo and change the default value in the header file of MarkerDetector.h

This did work, but the margin should  be a parameter, which is configurable in a roslaunch file.

Greetings,
  Stephan

**Comment by 130s** [comment]
This issue was moved to ros-perception/ar_track_alvar#23
