### ISSUE TITLE
Activate CI and automate tests

### ISSUE THREAD

**Issue by 130s** [sniekum/ar_track_alvar#73]
@sniekum Could you activate Travis CI for this repo? I think you can do that at https://travis-ci.org/profile/sniekum with a single click.
Then I'll open a PR for adding travis config.

**Comment by sniekum** [comment]
Done.

**Comment by 130s** [comment]
@sniekum Could you check again https://travis-ci.org/profile/sniekum and see if with `ar_track_alvar` Travis is enabled? Please make sure the package name is correct etc. (I know there's `ar_track_alvar_msgs` repository).

I've added the config for travis in #74. Travis should run with #74 but it isn't.

**Comment by 130s** [comment]
Sorry to bother you @sniekum, but could you check again if Travis is activated at:

https://travis-ci.org/profile/sniekum/ar_track_alvar_msgs/settings

and 

https://travis-ci.org/profile/sniekum/ar_track_alvar/settings

**Comment by 130s** [comment]
> @sniekum Could you check again https://travis-ci.org/profile/sniekum and see if with ar_track_alvar Travis is enabled? 

Sorry correct URLs is https://travis-ci.org/sniekum/

**Comment by sniekum** [comment]
Thought I did this a while back, but apparently I didn’t.  Should work now.  Let me know if there are any problems.

—Scott

**Comment by 130s** [comment]
Yes it's working, thanks!
