### ISSUE TITLE
Request for Kinetic Release

### ISSUE THREAD

**Issue by tfoote** [sniekum/ar_track_alvar#78]
@130s @sniekum could one of you release ar_track_alvar for kinetic? It's a dependency blocking our push towards a TurtleBot release. 

It should just be a matter of running bloom on the current version for kinetic. 

Thanks

**Comment by 130s** [comment]
Sure.

**Comment by 130s** [comment]
Done https://github.com/ros/rosdistro/pull/11716

**Comment by 130s** [comment]
@sniekum I made `kinetic-devel` branch because for kinetic we need to take care of OpenCV migration. Thus I incremented version to 0.6.x (jade and earlier are still in 0.5.x).
