### ISSUE TITLE
Release in hydro

### ISSUE THREAD

**Issue by jonbinney** [sniekum/ar_track_alvar#8]
@sniekum, any chance you could release this package for hydro? It shouldn't require any major changes, just creating a hydro-devel branch and doing the release.

**Comment by sniekum** [comment]
Binney,

I'm in the process of moving from New Orleans to Pittsburgh right now, so
the best I can do at the moment is make you a collaborator on the repo.
Hope things are going well over there.

--Scott

**Comment by jonbinney** [comment]
1. Thanks for giving me access to the repo; I'll do the release.
2. Pittsburgh??

**Comment by sniekum** [comment]
Yeah, I'm starting a postdoc at CMU!  And I also kind of love Pittsburgh.

**Comment by jonbinney** [comment]
congrats on the postdoc!

**Comment by jihoonl** [comment]
I am curious if there is any update on this issue. Do you guys plan this to release in hydro?

**Comment by jonbinney** [comment]
Hmmm.. just tried to do a release and bloom failed with rosdep unable to find dependency "pcl". Not sure why; if i use rosdep to install the dependencies of ar_track_alvar, it seems to work...

**Comment by jihoonl** [comment]
that's weird... did you get it working? or is there any way I can help?

**Comment by jonbinney** [comment]
Can you try to reproduce this to make sure its not just my setup? You just need to `sudo apt-get install python-bloom` and then `bloom-release ar_track_alvar --track hydro --rosdistro hydro --new-track` . When it tries to generate debians I get:

```
####
#### Generating 'precise' debian for package 'ar_track_alvar' at version '0.3.3-0'
####
Generating debian for precise...
Could not resolve rosdep key 'pcl'
Try to resolve the problem with rosdep and then continue.
Continue [Y/n]?
```

And if I tell it to continue it just repeats the error.

**Comment by jonbinney** [comment]
OK, fixed! I had forgotten to bump the version number in the package.xml, so it was checking out tag 0.3.3, which was actually on the groovy-devel branch, and did indeed depend on pcl.

**Comment by jonbinney** [comment]
I've done the release, here's the rosdistro PR: https://github.com/ros/rosdistro/pull/2641

**Comment by jihoonl** [comment]
awesome! thanks Jon!

**Comment by krisdestruction** [comment]
I get this error:

```
error: The requested URL returned error: 403 while accessing https://github.com/ros-gbp/ar_track_alvar-release.git/info/refs
fatal: HTTP request failed
Cannot push to remote release repository.

Following the webpage above, it comes out with this message:

Please upgrade your git client.
GitHub.com no longer supports git over dumb-http: https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days
```

**Comment by jonbinney** [comment]
What command gave you that error? Were you checking out the source code for the release repo?

**Comment by krisdestruction** [comment]
I should mention that after a bit of tinkering, I got my version installed correctly working using:
`sudo apt-get ros-hydro-ar-track-alvar`

However I got that error mentioned above using your method:
`sudo apt-get install python-bloom`
`bloom-release ar_track_alvar --track hydro --rosdistro hydro --new-track`

**Comment by jonbinney** [comment]
I was giving the command to trigger a new release of the package, not for installing it.

**Comment by jonbinney** [comment]
The release did eventually work, so you can just install from debs now.

**Comment by krisdestruction** [comment]
Okay as long as I got it working I'm fine with it.
