### ISSUE TITLE
Build fails on Kinetic

### ISSUE THREAD

**Issue by jackieokay** [sniekum/ar_track_alvar#81]
Please fix the ar_track_alvar package on the Kinetic buildfarm. If a fix isn't obvious I can blacklist the package for now.

http://build.ros.org/job/Kbin_uX64__ar_track_alvar__ubuntu_xenial_amd64__binary

**Comment by 130s** [comment]
Fixed via https://github.com/sniekum/ar_track_alvar/pull/84
