### ISSUE TITLE
how to track ar tag without camera frame

### ISSUE THREAD

**Issue by zfxw0206** [sniekum/ar_track_alvar#89]
Now I have a pointgrey camera which does not have camera frame. How cam I use ar track with this camera?

Thank you!

**Comment by mehditlili** [comment]
Just write anything in camera frame. The markers will be published with frame_id as what you set and if you want to see them in rviz just set your fixed frame to that same frame of the camera.

**Comment by zfxw0206** [comment]
Thank you. I set the id in the calibration yaml file. Then it is fine.

**Comment by 130s** [comment]
This issue was moved to ros-perception/ar_track_alvar#20
