### ISSUE TITLE
Double use of variable name compiler warning

### ISSUE THREAD

**Issue by AlexReimann** [sniekum/ar_track_alvar#95]
In ``FindMarkerBundlesNoKinect.cpp`` [one of the loops](https://github.com/sniekum/ar_track_alvar/blob/1823114d29b008b4cc222f345e29b2e594ec43ca/nodes/FindMarkerBundlesNoKinect.cpp#L228) of uses the same variable name for [a nested loop](https://github.com/sniekum/ar_track_alvar/blob/1823114d29b008b4cc222f345e29b2e594ec43ca/nodes/FindMarkerBundlesNoKinect.cpp#L259).

Code snippet:

````c++
      for (size_t i=0; i<marker_detector.markers->size(); i++)
	{
            ...

	    // Don't draw if it is a master tag...we do this later, a bit differently
	    bool should_draw = true;
	    for(int i=0; i<n_bundles; i++){
	      if(id == master_id[i]) should_draw = false;
	    }
            ...
	  }
	}
````

Not sure if 'fixing' this breaks something else

Could also use some formatting..

**Comment by 130s** [comment]
This issue was moved to ros-perception/ar_track_alvar#19
