### ISSUE TITLE
Marker Id over 30000 schould be 1-10

### ISSUE THREAD

**Issue by Monopolymer** [sniekum/ar_track_alvar#96]
I don´t get the right marker id. the same markers are rediscovered as different markers with ids over 10000.
I don't know what i am doing wrong.
please help

**Comment by mukeschShah** [comment]
@Monopolymer 
which version did you use? Maybe you suffer from the same issue mentioned in 
[ROS Indigo : version 0.5.4 resulting in erroneous tag detection #93](https://github.com/sniekum/ar_track_alvar/issues/93)

default marker_resolution switch in 0.5.4 from 5 to 7. And if you used 5x5 markers you getting marker_id mostly with id´s over 10000.

**Comment by Monopolymer** [comment]
Thank you going to version 0.5.3 solved my issue
